### ISSUE TITLE
Channel list viewer

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/wlm-ui#4]
### Feature you want to implement
For choosing channels to control or monitor, we need to implement channel list viewer.

### How the feature is implemented
It is a kind of list viewer, which consists of each channel.
Each is composed of simple explanation and checkbox to enable/disable the corresponding channel viewer.

Channels info will be served from `/channel/` implemented by snu-quiqcl/wlm-server#8.

**Comment by kangz12345** [comment]
For now, I will assume that the current channel selection is not preserved across devices.
For example, if I select some channels and close the browser, then they do not appear to be selected (i.e., reset) when I reopen the browser (or in an other device).
